blank_issues_enabled: false
contact_links:
  - name: 💬 Questions & discussions
    url: https://github.com/andreeyka/toggle-explorer-gitignore/discussions
    about: Ask questions and share ideas with the community.
